version: "3"
services:
  app:
    user: root
    tty: true
    restart: always
    build: . 
    working_dir: /IPv6Django
    command: bash -c "python manage.py makemigrations IPv6Django && python manage.py migrate IPv6Django && python3 manage.py runserver 0.0.0.0:8000 && chmod -R +x /IPv6Django"
    ports:
     - "8000:8000"
    volumes:
     - .:/IPv6Django
networks:
  example:
    enable_ipv6: true