# Generated by Django 3.2.5 on 2022-09-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv6TaskModel',
            fields=[
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_type', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('upload_path', models.CharField(max_length=300)),
                ('result_path', models.CharField(default='', max_length=300)),
                ('params', models.TextField(default='')),
                ('result', models.TextField(default='')),
            ],
            options={
                'db_table': 'tb_ipv6_task',
            },
        ),
    ]
